language: python

python:
  - 3.7

install:
  - make develop

script:
  # Code style checks.
  - make test-pycodestyle
  - make test-pylint

  # Unit tests.
  - make test-unittest

  # Build check.
  - make build